### ISSUE TITLE
Where is create_domain_tokenizer.py?

### ISSUE THREAD

**Issue by min-seon-kim** [xiaoleihuang/Neural_Temporality_Adaptation#2]
I can't find the create_domain_tokenizer.py file in your project indicated in README file.

Can you upload the python file?

**Comment by xiaoleihuang** [comment]
Thanks for the question... I remember that I rename the file name to [create_tokenizer.py](https://github.com/xiaoleihuang/Neural_Temporality_Adaptation/blob/master/create_tokenizer.py)

Let me know if that works.
